# Generated by Django 3.2.16 on 2024-04-21 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='name'),
        ),
    ]
